### ISSUE TITLE
Tutorial left side navigation only shows active tutorial

### ISSUE THREAD

**Issue by NukeManDan** [paritytechmarcomms/substrate-docs#19]
I would personally like to see a listing of tutorials on the navigation as it says "Tutorials" but only list the selected one from the tutorial cards page.
![image](https://user-images.githubusercontent.com/35669742/125556256-656616bf-f74f-4c1d-b0e0-2e1448f9ed54.png)

**Comment by dan-mayer** [comment]
- There should/will be a "back to" link. This will be universal across all implementations of the sidebar.
- I don't agree with removing the tutorials card page, personally. The tutorials are meant to be an easy entry point for relative novices. Dumping the user straight into a dense content page with TOC contained in sidebar works against this. 
- The general approach with regards to sidebars is that the left side bar shows all pages related to current 'unit of learning', whereas right sidebar shows anchor links within the current page. I think it's important to settle on a general system rather than trying to optimize each case (e.g. Tutorial, Doc, etc) in an ad-hoc way.

**Comment by NukeManDan** [comment]
Makes sense to me @dan-mayer - I think a  'Back to Tutorials' button in sidenav would fit the design principals you are after yes? If so, let's put in an issue outlining what changes (if any) should be make on the new repo:  https://github.com/substrate-developer-hub/substrate-docs
